version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "8000:8000"
    volumes:
      - .:/app/server
    env_file:
      - .env